config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get  "set_locale"                   => "locales#set_locale"

  scope '(:locale)', locale: /#{I18n.available_locales.reject { |l| l == I18n.default_locale}.join('|')}/ do
    get  ''            => 'welcome#index', :as => :home
    get  'about'        => 'welcome#about',      :as => :about
    get  'card_resources'       => 'cards#index',    :as => :cards
    get  'species_cards', to: redirect('/card_resources')
    get  'observer_cards' => "cards#observer_cards", :as => :observer_cards
    get  'lesson_plans' => 'lesson_plans#index', :as => :lesson_plans
    get  'lesson_plans/2-5_EnergyFlow1_PredatorsPrey.pdf', to: redirect('/lesson_plans/2-5_EnergyFlow1_PredatorsAndPrey.pdf')
    get  'lesson_plans/2-5_ScienceSkills_SkillBuilders4_ModelingClassification.pdf', to: redirect('/lesson_plans/2-5_ScienceSkills_BioblitzSkillbuilder4.pdf')
    get  'lesson_plans/:name' => 'lesson_plans#show', :as => :lesson_plan
    get  'earth_tours' => 'earth_tours#index', :as => :earth_tours

    resources :articles, :only => [:index]
    resources :users, :only => [:new, :create]

    get  "users/confirm/:token"         => "users#confirm", :as => :users_confirm
    get  "users/forgot_password"        => "users#forgot_password", :as => :forgot_password
    post "users/forgot_password"        => "users#mail_password_reset_token"
    get  "users/reset_password/:token"  => "users#reset_password_form", :as => :reset_password_form
    patch "users/reset_password/:token" => "users#reset_password"
    get "users/change_password"         => "users#change_password_form", :as => :change_password_form
    patch "users/change_password"       => "users#change_password"
    get "users/list"                    => "users#list"
    get "users/account"                 => "users#account", :as => :account
    get "users/typeahead/:q"            => "users#typeahead"
    get  "login"                        => "user_sessions#new"
    post "login"                        => "user_sessions#create"
    get  "logout"                       => "user_sessions#destroy"
    get  "user_sessions/user_info"      => "user_sessions#user_info"

    # Card maker
    post   "card_maker_ajax/cards"                    => "card_maker_ajax#create_card"
    post   "card_maker_ajax/decks/:deck_id/cards"     => "card_maker_ajax#create_deck_card"
    put    "card_maker_ajax/cards/:card_id/save"      => "card_maker_ajax#save_card"
    get    "card_maker_ajax/cards/:card_id(.:format)" => "card_maker_ajax#get_card"
    put    "card_maker_ajax/cards/:card_id/deck_id"   => "card_maker_ajax#set_card_deck"
    delete "card_maker_ajax/cards/:card_id/deck_id"   => "card_maker_ajax#remove_card_deck"
    post   "card_maker_ajax/cards/:card_id/refresh_images" => "card_maker_ajax#refresh_card_images"
#    get    "card_maker_ajax/card_ids"                 => "card_maker_ajax#card_ids"
    get    "card_maker_ajax/cards"                    => "card_maker_ajax#cards"
    get    "card_maker_ajax/decks/:deck_id/card_ids"  => "card_maker_ajax#deck_card_ids"
    post   "card_maker_ajax/decks"                    => "card_maker_ajax#create_deck"
    get    "card_maker_ajax/decks"                    => "card_maker_ajax#decks"
    post   "card_maker_ajax/images"                   => "card_maker_ajax#upload_image"
    get    "card_maker_ajax/templates/:template_name/:template_version" => "card_maker_ajax#template",
      :constraints => { :template_version => /\d\.\d/ }
    delete "card_maker_ajax/cards/:card_id"           => "card_maker_ajax#delete_card"
    get    "card_maker_ajax/decks/:deck_id"           => "card_maker_ajax#get_deck"
    delete "card_maker_ajax/decks/:deck_id"           => "card_maker_ajax#delete_deck"
    get    "card_maker_ajax/taxon_search/:query"      => "card_maker_ajax#taxon_search", constraints: { query: /[^\/]*/ }
    post   "card_maker_ajax/decks/:id/populateFromCollection" => "card_maker_ajax#populate_deck_from_collection"
    get    "card_maker_ajax/collectionJob/:id/status" => "card_maker_ajax#collection_job_status"
    post   "card_maker_ajax/deck_pdfs"                => "card_maker_ajax#create_deck_pdf"
    get    "card_maker_ajax/deck_pdfs/:id/status"     => "card_maker_ajax#deck_pdf_status"
    get    "card_maker_ajax/deck_pdfs/downloads/:file_name" => "card_maker_ajax#deck_pdf_result", format: false, constraints: { file_name: /[^\/]*/ }
    p
    post   "card_maker_ajax/deck_pngs"                => "card_maker_ajax#create_deck_pngs"
    get    "card_maker_ajax/deck_pngs/:id/status"     => "card_maker_ajax#deck_png_status"
    get    "card_maker_ajax/deck_pngs/downloads/:file_name" => "card_maker_ajax#deck_png_result", format: false, constraints: { file_name: /[^\/]*/ }
    post   "card_maker_ajax/decks/:deck_id/desc"      => "card_maker_ajax#set_deck_desc"
    post   "card_maker_ajax/decks/:deck_id/make_public" => "card_maker_ajax#make_deck_public"
    post   "card_maker_ajax/decks/:deck_id/make_private" => "card_maker_ajax#make_deck_private"
    post   "card_maker_ajax/decks/:deck_id/users"     => "card_maker_ajax#add_deck_user"
    delete "card_maker_ajax/decks/:deck_id/users/:user_id" => "card_maker_ajax#remove_deck_user"
    get    "card_maker_ajax/decks/:deck_id/users"     => "card_maker_ajax#deck_users"
    get    "card_maker_ajax/public/cards"             => "card_maker_ajax#public_cards"
    get    "card_maker_ajax/public/decks"             => "card_maker_ajax#public_decks"
    post   "card_maker_ajax/decks/:deck_id/name/"     => "card_maker_ajax#rename_deck"
    get    "card_maker_ajax/card_backs"               => "card_maker_ajax#card_backs"
    get    "card_maker_ajax/cached_images/:img_url"   => "card_maker_ajax#cached_image", constraints: { img_url: /.+/ }
    get    "card_maker_ajax/taxa/:taxon_id/cards/public" => "card_maker_ajax#public_cards_for_taxon"
    get    "card_maker"                               => "card_maker#index", :as => :card_maker

    get "podcasts" => "podcasts#index", :as => "podcasts"
    get "podcasts/rss.xml" => "podcasts#rss"
    get "podcasts/:slug", to: redirect("/podcasts#%{slug}", status: 302), as: "podcast"
    get "podcast_category_groups" => "podcast_category_groups#index", :as => "podcast_category_groups"
  end

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/user.rb
require "unix_crypt"

class User < ApplicationRecord
  ##########################################################
  # DO NOT ALTER MAPPINGS - ONLY ADD NEW ONES AS NECESSARY #
  ##########################################################
  enum :role => {
    :basic => 0,
    :admin => 1,
  }

  has_secure_password :validations => false

  # Constants used in view for HTML5 pattern validation
  PASSWORD_MIN_LENGTH = 6
  validates :password, :length => { minimum: PASSWORD_MIN_LENGTH },
                       :confirmation => true,
                       :if => :validate_password?

  validates :password_confirmation, :presence => true,
                                    :unless => :password_blank?

  USER_NAME_PATTERN = "[a-zA-Z0-9\.@_]+"
  validates :user_name, :presence => true,
                        :uniqueness => true,
                        :format => { :with =>/\A#{USER_NAME_PATTERN}\z/ }

  validates :email, :presence => true
  validates :full_name, :presence => true
  validates :confirm_token, :presence => true, :uniqueness => true
  validates :role, :presence => true

  has_many :password_reset_tokens

  before_validation :set_confirm_token
  before_validation :set_default_role

  attr_accessor :force_password_validation

  def locale
    saved_locale = read_attribute(:locale)
    if saved_locale
      saved_locale
    else
      I18n.default_locale
    end
  end

  # Set confirmed_at to the current time and save
  def confirm!
    if confirmed_at
      raise "User already confirmed"
    end

    self.confirmed_at = DateTime.now
    save!
  end

  def confirmed?
    confirmed_at.present?
  end

  # Hack to allow controllers to add current_password errors, for
  # example, when requiring the user's current password when changing
  # it.
  def current_password
    nil
  end

  private
  def validate_password?
    force_password_validation || !persisted? || !password.blank?
  end

  def password_blank?
    password.blank?
  end

  def set_confirm_token
    self.confirm_token ||= SecureRandom.base64
  end

  def set_default_role
    self.role ||= :basic
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :ensure_admin, :only => [ :list ]
  before_action :ensure_user, :only => [:change_password_form, :change_password, :show, :account, :typeahead]
  before_action :set_password_reset_vars, :only => [:reset_password_form, :reset_password]

  MIN_TYPEAHEAD_LEN = 3

  # GET /users/new
  def new
    @user = User.new
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    recaptcha_token = params[:'g-recaptcha-response']


    if recaptcha_token.blank?
      logger.error('encountered user signup without recaptcha token -- failing request')
      return render file: 'public/400.html', layout: false, status: :bad_request
    end

    if !RecaptchaVerifier.new(recaptcha_token).success?
      logger.error('got a failed recaptcha response')
      return render file: 'public/400.html', layout: false, status: :bad_request
    end

    respond_to do |format|
      if @user.save
        SignupConfirmationMailer.confirmation_email(@user).deliver_now
        format.html { render :confirmation_pending }
        format.json do
          render :json => {
            :success => true,
            :msg => t("welcome.index.accounts.signup_success_msg")
          }
        end
      else
        format.html { render :new }

        format.json do
          render :json => {
            :success => false,
            :msg => t("welcome.index.accounts.signup_failure_msg"),
            :errors => @user.errors
          }
        end
      end
    end
  end

  def account
  end

  def confirm
    @user = User.find_by_confirm_token!(params[:token])

    if !@user.confirmed?
      @user.confirm!
      flash[:notice] = t(".success", :user_name => @user.user_name)
      redirect_to login_path
    else
      raise NotFoundError
    end
  end

  def forgot_password
  end

  def mail_password_reset_token
    @user = User.find_by_user_name(params[:user_name])

    if @user && @user.confirmed?
      token = PasswordResetToken.create_for_user(@user)
      ForgotPasswordMailer.forgot_password_email(token).deliver_now
    else
      @error_msg = t(".invalid_user_name")
      render :forgot_password
    end
  end

  def change_password_form
    @user = logged_in_user
  end

  def change_password
    @user = logged_in_user
    auth_success = @user.authenticate(params[:user][:current_password])

    if !auth_success
      @user.errors.add(:current_password, :invalid)
    end

    success = auth_success && 
      @user.update(change_password_params.merge(:force_password_validation => true))

    if success
      flash[:notice] = t(".success")
      redirect_to account_path
    else
      render :change_password_form
    end
  end

  def reset_password_form
  end

  def reset_password
    change_password_shared
  end

  def reset_password
    if @user.update(change_password_params.merge(:force_password_validation => true))
      @reset_token.mark_used if @reset_token
      flash[:notice] = t(".success")
      redirect_to login_path
    else
      render :reset_password_form
    end
  end

  def email_test
    @user = User.first
    render :confirmation_pending
  end

  def list
    respond_to do |format|
      format.json do
        @user_data = User.order(:user_name).map do |u|
          { 
            :userName => u.user_name, 
            :id => u.id 
          } 
        end

        render :json => @user_data
      end
    end
  end

  def typeahead
    json = if params[:q].length >= MIN_TYPEAHEAD_LEN
      User.where("UPPER(user_name) LIKE ?", "#{params[:q].upcase}%")
      .pluck(:id, :user_name)
      .map { |pair| { :id => pair[0], :label => pair[1] } }
    else
      []
    end
    render :json => json
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def set_password_reset_vars
      @reset_token = PasswordResetToken.find_valid_by_token(params[:token])
      @user = @reset_token.user
    end

    def user_params
      params.fetch(:user, {}).permit(:email, :user_name, :full_name, :password, :password_confirmation)
    end

    def change_password_params
      params.fetch(:user, {}).permit(:password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_errors.haml
- if @user.errors.any?
  %ul.errors
    - @user.errors.full_messages.each do |message|
      %li.txt= message

app/views/users/_password_fields.haml
= f.password_field :password,
    :pattern  => ".{#{User::PASSWORD_MIN_LENGTH},}",
    :required => true,
    :title    => t_model_error(:user, :password, :too_short,
                               :count => User::PASSWORD_MIN_LENGTH),
    :class    => "input block",
    :placeholder => true
= f.password_field :password_confirmation, 
  :required => true, 
  :class => "input block", 
  :placeholder => true

app/views/users/account.haml
.l-account
  -if notice
    .user-card.user-card-notice= notice
  .user-card
    .user-card-user-name= logged_in_user.user_name
    .user-card-full-name= logged_in_user.full_name

    .user-card-bottom
      .user-card-email= logged_in_user.email
      = link_to t(".change_password"), change_password_form_path, :class => "std-link"

app/views/users/change_password_form.haml
.l-form-box
  %h1= t(".change_password")

  = render "errors"

  = form_for(@user,
    { :html => { :class => "form" },
      :url => { :action => :change_password } }) do |f|
    = f.password_field :current_password, :class => "input block", :placeholder => t(".current_password")
    = render :partial => "password_fields", :locals => { :f => f }

    = f.submit t(".change_password"), :class => "submit block"

app/views/users/confirmation_pending.haml
.l-form-box
  %p.txt= t(".check_your_email", :user_name => @user.user_name, :email => @user.email)

app/views/users/forgot_password.haml
.l-form-box
  %h1= t(".header")

  - if @error_msg
    %p.txt.txt-block= @error_msg

  = form_tag forgot_password_path, :class => "form" do
    = text_field_tag :user_name, 
      nil, 
      :class => "input block", 
      :placeholder => t("activerecord.attributes.user.user_name")
    = submit_tag t(".submit"), :class => "submit block"

app/views/users/forgot_password_email.html.erb
<p><%= t(".email_sent") %></p>

app/views/users/mail_password_reset_token.haml
.l-form-box
  %p.txt= t(".email_sent")

app/views/users/new.haml
.l-form-box
  %h1= t(".sign_up")

  = render "errors"

  = form_for(@user, :html => { :id => "user-form", :class => "form" }) do |f|
    = f.email_field :email, :required => true, :class => "input block", :placeholder => true
    = f.text_field :user_name,
        :pattern  => User::USER_NAME_PATTERN,
        :required => true,
        :title    => t_model_error(:user, :user_name, :invalid),
        :class    => "input block",
        :placeholder => true

    = f.text_field :full_name, :required => true, :class => "input block", :placeholder => true
    = render :partial => "password_fields", :locals => { :f => f}
    = f.submit t(".sign_up"), :class => "submit block g-recaptcha", :data => { :sitekey => '6LdeYEAaAAAAAJxY8nbvin1Lr2-8am6BJP2LLdFp', :callback => 'onNewUserSubmit', :action => 'submit' }

app/views/users/reset_password.html.erb
<h1><%= t(".header") %></h1>

<%= form_for @user, :url => { :action => :reset_password } do |f| %>
  <%= render "errors" %>

  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= f.submit t(".header") %>
  </div>
<% end %>

app/views/users/reset_password_form.haml
.l-form-box
  %h1= t(".header")

  = render "errors"

  = form_for(@user,
    { :url => { :action => :reset_password },
      :html => { :class => "form" } }) do |f|

    = render :partial => "password_fields", :locals => { :f => f }

    = f.submit t(".header"), :class => "submit block"