config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get  "set_locale"                   => "locales#set_locale"

  scope '(:locale)', locale: /#{I18n.available_locales.reject { |l| l == I18n.default_locale}.join('|')}/ do
    get  ''            => 'welcome#index', :as => :home
    get  'about'        => 'welcome#about',      :as => :about
    get  'card_resources'       => 'cards#index',    :as => :cards
    get  'species_cards', to: redirect('/card_resources')
    get  'observer_cards' => "cards#observer_cards", :as => :observer_cards
    get  'lesson_plans' => 'lesson_plans#index', :as => :lesson_plans
    get  'lesson_plans/2-5_EnergyFlow1_PredatorsPrey.pdf', to: redirect('/lesson_plans/2-5_EnergyFlow1_PredatorsAndPrey.pdf')
    get  'lesson_plans/2-5_ScienceSkills_SkillBuilders4_ModelingClassification.pdf', to: redirect('/lesson_plans/2-5_ScienceSkills_BioblitzSkillbuilder4.pdf')
    get  'lesson_plans/:name' => 'lesson_plans#show', :as => :lesson_plan
    get  'earth_tours' => 'earth_tours#index', :as => :earth_tours

    resources :articles, :only => [:index]
    resources :users, :only => [:new, :create]

    get  "users/confirm/:token"         => "users#confirm", :as => :users_confirm
    get  "users/forgot_password"        => "users#forgot_password", :as => :forgot_password
    post "users/forgot_password"        => "users#mail_password_reset_token"
    get  "users/reset_password/:token"  => "users#reset_password_form", :as => :reset_password_form
    patch "users/reset_password/:token" => "users#reset_password"
    get "users/change_password"         => "users#change_password_form", :as => :change_password_form
    patch "users/change_password"       => "users#change_password"
    get "users/list"                    => "users#list"
    get "users/account"                 => "users#account", :as => :account
    get "users/typeahead/:q"            => "users#typeahead"
    get  "login"                        => "user_sessions#new"
    post "login"                        => "user_sessions#create"
    get  "logout"                       => "user_sessions#destroy"
    get  "user_sessions/user_info"      => "user_sessions#user_info"

    # Card maker
    post   "card_maker_ajax/cards"                    => "card_maker_ajax#create_card"
    post   "card_maker_ajax/decks/:deck_id/cards"     => "card_maker_ajax#create_deck_card"
    put    "card_maker_ajax/cards/:card_id/save"      => "card_maker_ajax#save_card"
    get    "card_maker_ajax/cards/:card_id(.:format)" => "card_maker_ajax#get_card"
    put    "card_maker_ajax/cards/:card_id/deck_id"   => "card_maker_ajax#set_card_deck"
    delete "card_maker_ajax/cards/:card_id/deck_id"   => "card_maker_ajax#remove_card_deck"
    post   "card_maker_ajax/cards/:card_id/refresh_images" => "card_maker_ajax#refresh_card_images"
#    get    "card_maker_ajax/card_ids"                 => "card_maker_ajax#card_ids"
    get    "card_maker_ajax/cards"                    => "card_maker_ajax#cards"
    get    "card_maker_ajax/decks/:deck_id/card_ids"  => "card_maker_ajax#deck_card_ids"
    post   "card_maker_ajax/decks"                    => "card_maker_ajax#create_deck"
    get    "card_maker_ajax/decks"                    => "card_maker_ajax#decks"
    post   "card_maker_ajax/images"                   => "card_maker_ajax#upload_image"
    get    "card_maker_ajax/templates/:template_name/:template_version" => "card_maker_ajax#template",
      :constraints => { :template_version => /\d\.\d/ }
    delete "card_maker_ajax/cards/:card_id"           => "card_maker_ajax#delete_card"
    get    "card_maker_ajax/decks/:deck_id"           => "card_maker_ajax#get_deck"
    delete "card_maker_ajax/decks/:deck_id"           => "card_maker_ajax#delete_deck"
    get    "card_maker_ajax/taxon_search/:query"      => "card_maker_ajax#taxon_search", constraints: { query: /[^\/]*/ }
    post   "card_maker_ajax/decks/:id/populateFromCollection" => "card_maker_ajax#populate_deck_from_collection"
    get    "card_maker_ajax/collectionJob/:id/status" => "card_maker_ajax#collection_job_status"
    post   "card_maker_ajax/deck_pdfs"                => "card_maker_ajax#create_deck_pdf"
    get    "card_maker_ajax/deck_pdfs/:id/status"     => "card_maker_ajax#deck_pdf_status"
    get    "card_maker_ajax/deck_pdfs/downloads/:file_name" => "card_maker_ajax#deck_pdf_result", format: false, constraints: { file_name: /[^\/]*/ }
    p
    post   "card_maker_ajax/deck_pngs"                => "card_maker_ajax#create_deck_pngs"
    get    "card_maker_ajax/deck_pngs/:id/status"     => "card_maker_ajax#deck_png_status"
    get    "card_maker_ajax/deck_pngs/downloads/:file_name" => "card_maker_ajax#deck_png_result", format: false, constraints: { file_name: /[^\/]*/ }
    post   "card_maker_ajax/decks/:deck_id/desc"      => "card_maker_ajax#set_deck_desc"
    post   "card_maker_ajax/decks/:deck_id/make_public" => "card_maker_ajax#make_deck_public"
    post   "card_maker_ajax/decks/:deck_id/make_private" => "card_maker_ajax#make_deck_private"
    post   "card_maker_ajax/decks/:deck_id/users"     => "card_maker_ajax#add_deck_user"
    delete "card_maker_ajax/decks/:deck_id/users/:user_id" => "card_maker_ajax#remove_deck_user"
    get    "card_maker_ajax/decks/:deck_id/users"     => "card_maker_ajax#deck_users"
    get    "card_maker_ajax/public/cards"             => "card_maker_ajax#public_cards"
    get    "card_maker_ajax/public/decks"             => "card_maker_ajax#public_decks"
    post   "card_maker_ajax/decks/:deck_id/name/"     => "card_maker_ajax#rename_deck"
    get    "card_maker_ajax/card_backs"               => "card_maker_ajax#card_backs"
    get    "card_maker_ajax/cached_images/:img_url"   => "card_maker_ajax#cached_image", constraints: { img_url: /.+/ }
    get    "card_maker_ajax/taxa/:taxon_id/cards/public" => "card_maker_ajax#public_cards_for_taxon"
    get    "card_maker"                               => "card_maker#index", :as => :card_maker

    get "podcasts" => "podcasts#index", :as => "podcasts"
    get "podcasts/rss.xml" => "podcasts#rss"
    get "podcasts/:slug", to: redirect("/podcasts#%{slug}", status: 302), as: "podcast"
    get "podcast_category_groups" => "podcast_category_groups#index", :as => "podcast_category_groups"
  end

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/shared/_draft_header.html.erb
<% if draft_page? %>
  <div id="DraftHeader">This is a draft view of this page. Click <%= link_to "here", published_path %> to navigate to the live version.</div>
<% elsif draftable_page? %>
  <div id="DraftHeader">This is the live version of this page. Click <%= link_to "here", draft_path %> to edit.</div>
<% end %>

app/views/shared/_footer.haml
.footer
  = link_to "https://naturalhistory.si.edu" do
    = image_tag "welcome/nmnh_logo_bw.png", :alt => t(".nmnh_logo_alt"), :class => "mcz-logo"
  .addr-line.top= t ".nmnh_contact_html"

app/views/shared/_header.haml
.navbar-outer.js-navbar.js-fixed
  .navbar.navbar-top<
    .navbar-inner
      .l-abs-l
        .nav-menu.nav-menu-eol
          = link_to home_path, :class => "home-lnk" do
            = image_tag "welcome/eol_logo.png", :class => "eol-logo"
            %i.fa.fa-caret-down.nav-menu-caret
          %ul.eol-dropdown
            %li.eol-link.selected
              = link_to t(".eol_nav.l_and_e"), home_path
            %li.eol-link
              = link_to t(".eol_nav.eol"), "http://www.eol.org"
        = render :partial => "shared/lang_select", :locals => { :extra_class => "lang-menu-nav" }
      .l-abs-r
        .nav-user
          = render :partial => "shared/user_links", :locals => { :top_class => "user-links-nav" }
          .nav-user-menu-toggle.js-slide-menu-toggle
            %i.fa.fa-bars.fa-lg
      %h1#Title.title 
        = t ".main_title"
  - unless @header_slim
    .navbar.navbar-bottom<
      .navbar-inner
        = render "shared/nav_items", menu_class: "nav-lnks", sub_menu_base_class: "nav-lnk-menu", item_class: "nav-lnk", down_arrows: true

app/views/shared/_hero_image.haml
.hero-shim
  .hero-shim-inner{:style => "background-image: url(#{image_path large});" }
.hero-full{ :style => "background-image: url(#{image_path large});" }
.hero-small{ :style => "background-image: url(#{image_path small});"}

app/views/shared/_hero_placeholder.haml
%img{:src => "https://placekitten.com/1140/349"}

app/views/shared/_hero_slim.haml
= image_tag (image || "shared/banner_slim.png"), class: "hero-slim"

app/views/shared/_image_credits.haml
#ImageCredits.image-credits-section
  %h2.image-credits-hdr= t ".header"
  %p.image-credits-text.image-credits-overview= t ".eol_promotes_html"
  .image-credits.image-credits-text
    -images.each do |image|
      .image-credit
        - if image.key?(:url)
          = t ".credit_html", :title => image[:title],
            :title_class => "image-title",
            :author => image[:author],
            :source => image[:source],
            :url => image[:url],
            :license => image[:license]
        - elsif image.key?(:source)
          = t ".credit_nolink_html", :title => image[:title],
            :title_class => "image-title",
            :author => image[:author],
            :source => image[:source],
            :license => image[:license]
        - else
          = t ".credit_nosource_html", :title => image[:title],
            :title_class => "image-title",
            :author => image[:author],
            :license => image[:license]

app/views/shared/_intro_section.haml
.intro{class: local_assigns.fetch(:class, "")}
  %h1.intro-hdr= t header
  - paragraphs.each do |para|
    %p.text.text-p
      - if para.is_a? String
        = t para
      - else 
        -# Hash is the only other accepted type
        = t para[:key], para[:vars]

app/views/shared/_lang_select.haml
%ul.nav-menu.lang-menu.js-lang-menu{ :class => extra_class }
  %li.lang-item
    %span= t("language")
    %i.fa.fa-caret-down.nav-menu-caret.nav-menu-caret-lang.nav-menu-caret-down
    %i.fa.fa-caret-up.nav-menu-caret.nav-menu-caret-lang.nav-menu-caret-up
  - I18n.available_locales.sort.each do |locale|
    %li.lang-item.lang-item-choice
      - if I18n.locale != locale
        = link_to(I18n.t("language", :locale => locale), set_locale_path(:params => { :set_locale => locale }))

app/views/shared/_mob_menu.haml
.js-slide-menu.slide-menu
  = render :partial => "shared/user_links", :locals => { :top_class => "user-links-slide" }
  = render :partial => "shared/lang_select", :locals => { :extra_class => "lang-menu-slide" }
  = render "shared/nav_items", menu_class: "nav-lnks-mob", item_class: "nav-lnk-mob", sub_menu_base_class: "nav-lnk-menu-mob", down_arrows: false

app/views/shared/_nav_items.haml
%ul{class: menu_class}
  %li{class: item_class}
    %span.nav-lnk-txt
      = t(".biodiversity_cards")
      - if down_arrows
        %i.fa.fa-caret-down.nav-lnk-down
    %ul{class: [sub_menu_base_class, "#{sub_menu_base_class}-cards"]}
      %li= link_to(t(".card_resources"), cards_path)
      %li= link_to(t(".card_maker"), card_maker_path)
      %li= link_to(t(".observer_cards"), observer_cards_path)
  %li{class: item_class}
    %span.nav-lnk-txt
      = t(".lesson_plans")
      - if down_arrows
        %i.fa.fa-caret-down.nav-lnk-down
    %ul{class: [sub_menu_base_class, "#{sub_menu_base_class}-lesson"]}
      %li= link_to(t(".overview"), lesson_plans_path + "#")
      %li= link_to(t(".grades_2_5"), lesson_plans_path(anchor: "grade_level=0"))
      %li= link_to(t(".grades_6_8"), lesson_plans_path(anchor: "grade_level=1"))
      %li= link_to(t(".grades_9_12"), lesson_plans_path(anchor: "grade_level=2"))
  %li{class: item_class}
    %span.nav-lnk-txt= link_to(t(".podcasts"), podcasts_path)
  %li{class: item_class}
    %span.nav-lnk-txt= link_to(t(".google_earth_tours"), earth_tours_path)
  %li{class: item_class}
    %span.nav-lnk-txt
      = t(".more")
      - if down_arrows
        %i.fa.fa-caret-down.nav-lnk-down
    %ul{class: [sub_menu_base_class, "#{sub_menu_base_class}-partner"]}
      %li= link_to(t(".articles"), articles_path)
      %li= link_to(t(".about_eol"), about_path)
      %li= link_to(t(".inaturalist_html"), "https://www.inaturalist.org/")
      %li= link_to(t(".bhl_coloring_html"), "https://drive.google.com/file/d/0B00hDkSQMhfDMXdIVng0NGd0WlU/view")
      %li= link_to(t(".cnc_html"), "http://citynaturechallenge.org/education-toolkit/")

app/views/shared/_published_locale_fields.html.erb
<div class="field">
  <div>Published locales</div>
  <% I18n.available_locales.each do |locale| %>
    <%= check_box_tag("published_locales[]", locale, model.published_in_locale?(locale)) %>
    <%= label_tag("published_locales[]", locale) %>
  <% end %>
</div>

app/views/shared/_section_head.haml
%div{:class => ["section-head", ("section-head-top" if local_assigns[:top])], :id => (id if local_assigns[:id])}
  %h2.section-title
    = t title_key

app/views/shared/_user_links.haml
%div{:class => top_class}
  -if logged_in_user
    = link_to(logged_in_user.user_name, account_path, :class => "nav-link nav-link-account")
    = link_to(t("shared.header.sign_out"), logout_path, :class => "nav-link nav-link-sign-out")
  -else
    = link_to t("shared.header.sign_in"), login_path, :class => "nav-link nav-link-account"