config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get  "set_locale"                   => "locales#set_locale"

  scope '(:locale)', locale: /#{I18n.available_locales.reject { |l| l == I18n.default_locale}.join('|')}/ do
    get  ''            => 'welcome#index', :as => :home
    get  'about'        => 'welcome#about',      :as => :about
    get  'card_resources'       => 'cards#index',    :as => :cards
    get  'species_cards', to: redirect('/card_resources')
    get  'observer_cards' => "cards#observer_cards", :as => :observer_cards
    get  'lesson_plans' => 'lesson_plans#index', :as => :lesson_plans
    get  'lesson_plans/2-5_EnergyFlow1_PredatorsPrey.pdf', to: redirect('/lesson_plans/2-5_EnergyFlow1_PredatorsAndPrey.pdf')
    get  'lesson_plans/2-5_ScienceSkills_SkillBuilders4_ModelingClassification.pdf', to: redirect('/lesson_plans/2-5_ScienceSkills_BioblitzSkillbuilder4.pdf')
    get  'lesson_plans/:name' => 'lesson_plans#show', :as => :lesson_plan
    get  'earth_tours' => 'earth_tours#index', :as => :earth_tours

    resources :articles, :only => [:index]
    resources :users, :only => [:new, :create]

    get  "users/confirm/:token"         => "users#confirm", :as => :users_confirm
    get  "users/forgot_password"        => "users#forgot_password", :as => :forgot_password
    post "users/forgot_password"        => "users#mail_password_reset_token"
    get  "users/reset_password/:token"  => "users#reset_password_form", :as => :reset_password_form
    patch "users/reset_password/:token" => "users#reset_password"
    get "users/change_password"         => "users#change_password_form", :as => :change_password_form
    patch "users/change_password"       => "users#change_password"
    get "users/list"                    => "users#list"
    get "users/account"                 => "users#account", :as => :account
    get "users/typeahead/:q"            => "users#typeahead"
    get  "login"                        => "user_sessions#new"
    post "login"                        => "user_sessions#create"
    get  "logout"                       => "user_sessions#destroy"
    get  "user_sessions/user_info"      => "user_sessions#user_info"

    # Card maker
    post   "card_maker_ajax/cards"                    => "card_maker_ajax#create_card"
    post   "card_maker_ajax/decks/:deck_id/cards"     => "card_maker_ajax#create_deck_card"
    put    "card_maker_ajax/cards/:card_id/save"      => "card_maker_ajax#save_card"
    get    "card_maker_ajax/cards/:card_id(.:format)" => "card_maker_ajax#get_card"
    put    "card_maker_ajax/cards/:card_id/deck_id"   => "card_maker_ajax#set_card_deck"
    delete "card_maker_ajax/cards/:card_id/deck_id"   => "card_maker_ajax#remove_card_deck"
    post   "card_maker_ajax/cards/:card_id/refresh_images" => "card_maker_ajax#refresh_card_images"
#    get    "card_maker_ajax/card_ids"                 => "card_maker_ajax#card_ids"
    get    "card_maker_ajax/cards"                    => "card_maker_ajax#cards"
    get    "card_maker_ajax/decks/:deck_id/card_ids"  => "card_maker_ajax#deck_card_ids"
    post   "card_maker_ajax/decks"                    => "card_maker_ajax#create_deck"
    get    "card_maker_ajax/decks"                    => "card_maker_ajax#decks"
    post   "card_maker_ajax/images"                   => "card_maker_ajax#upload_image"
    get    "card_maker_ajax/templates/:template_name/:template_version" => "card_maker_ajax#template",
      :constraints => { :template_version => /\d\.\d/ }
    delete "card_maker_ajax/cards/:card_id"           => "card_maker_ajax#delete_card"
    get    "card_maker_ajax/decks/:deck_id"           => "card_maker_ajax#get_deck"
    delete "card_maker_ajax/decks/:deck_id"           => "card_maker_ajax#delete_deck"
    get    "card_maker_ajax/taxon_search/:query"      => "card_maker_ajax#taxon_search", constraints: { query: /[^\/]*/ }
    post   "card_maker_ajax/decks/:id/populateFromCollection" => "card_maker_ajax#populate_deck_from_collection"
    get    "card_maker_ajax/collectionJob/:id/status" => "card_maker_ajax#collection_job_status"
    post   "card_maker_ajax/deck_pdfs"                => "card_maker_ajax#create_deck_pdf"
    get    "card_maker_ajax/deck_pdfs/:id/status"     => "card_maker_ajax#deck_pdf_status"
    get    "card_maker_ajax/deck_pdfs/downloads/:file_name" => "card_maker_ajax#deck_pdf_result", format: false, constraints: { file_name: /[^\/]*/ }
    p
    post   "card_maker_ajax/deck_pngs"                => "card_maker_ajax#create_deck_pngs"
    get    "card_maker_ajax/deck_pngs/:id/status"     => "card_maker_ajax#deck_png_status"
    get    "card_maker_ajax/deck_pngs/downloads/:file_name" => "card_maker_ajax#deck_png_result", format: false, constraints: { file_name: /[^\/]*/ }
    post   "card_maker_ajax/decks/:deck_id/desc"      => "card_maker_ajax#set_deck_desc"
    post   "card_maker_ajax/decks/:deck_id/make_public" => "card_maker_ajax#make_deck_public"
    post   "card_maker_ajax/decks/:deck_id/make_private" => "card_maker_ajax#make_deck_private"
    post   "card_maker_ajax/decks/:deck_id/users"     => "card_maker_ajax#add_deck_user"
    delete "card_maker_ajax/decks/:deck_id/users/:user_id" => "card_maker_ajax#remove_deck_user"
    get    "card_maker_ajax/decks/:deck_id/users"     => "card_maker_ajax#deck_users"
    get    "card_maker_ajax/public/cards"             => "card_maker_ajax#public_cards"
    get    "card_maker_ajax/public/decks"             => "card_maker_ajax#public_decks"
    post   "card_maker_ajax/decks/:deck_id/name/"     => "card_maker_ajax#rename_deck"
    get    "card_maker_ajax/card_backs"               => "card_maker_ajax#card_backs"
    get    "card_maker_ajax/cached_images/:img_url"   => "card_maker_ajax#cached_image", constraints: { img_url: /.+/ }
    get    "card_maker_ajax/taxa/:taxon_id/cards/public" => "card_maker_ajax#public_cards_for_taxon"
    get    "card_maker"                               => "card_maker#index", :as => :card_maker

    get "podcasts" => "podcasts#index", :as => "podcasts"
    get "podcasts/rss.xml" => "podcasts#rss"
    get "podcasts/:slug", to: redirect("/podcasts#%{slug}", status: 302), as: "podcast"
    get "podcast_category_groups" => "podcast_category_groups#index", :as => "podcast_category_groups"
  end

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  def index
    @hero_image_partial = "shared/hero_slim"

    @food_chains_rummy = LessonPlan.find_by_human_name!("food_chains_rummy_9_12")
    @go_adapt = LessonPlan.find_by_human_name!("go_adapt_2_5")
    @thats_classified = LessonPlan.find_by_human_name!("thats_classified_2_5")
    @create_a_creature = LessonPlan.find_by_human_name!("create_a_creature_2_5")
  end

  def observer_cards
    @banner_image = "cards/bee_banner.png"
  end
end

app/helpers/cards_helper.rb
module CardsHelper
  def scroll_to_deck_path(deck)
    cards_path :anchor => "scroll_to=#{deck.id}"
  end

  def how_to_path(key)
    "cards.index.how_to.#{key}"
  end
end

app/views/cards/_activity.haml
%li.lesson-plan
  = link_to lesson_plan_path(name: lesson_plan.human_name) do
    .lesson-plan-text.text= text

app/views/cards/_card.haml
%li.card
  - if local_assigns.include? :file_path
    = link_to file_path do
      = image_tag "cards/#{image_file_name}", class: "card-img"
      .card-name= name
      %p.card-desc.text= desc
  - else
    = image_tag "cards/#{image_file_name}", class: "card-img"
    .card-name= name
    %p.card-desc.text= desc

app/views/cards/_cards_hero.haml
= render "shared/hero_image", :large => "cards/hero.jpg",
  :small => "cards/hero_sm.jpg"

app/views/cards/_deck.haml
%li{:class => ["deck", ("odd" if index % 2 == 0), ("even" if index % 2 == 1)], :id => "Deck#{deck.id}"}>
  = image_tag "cards/#{deck.image_file_name}.png", :class => "deck-img"
  .deck-info>
    %h3.deck-title= deck.localized_title
    -if deck.localized_subtitle
      %h4.deck-sub= deck.localized_subtitle
    -else
      .deck-sub-placeholder

    %p.deck-desc= deck.localized_desc
    =link_to deck_pdf_path(deck.file_name), :class => "pdf-button", :download => "" do 
      %i.fa.fa-download.fa-lg

app/views/cards/_featured.haml
%li{:class => "featured-deck hoverable #{class_str}"}
  = link_to deck_pdf_path(file_name), :download => "" do
    %div{:class => "download-button #{color}"}
      %i.fa.fa-download.download-icon
    .featured-deck-wrap
      =image_tag "cards/#{image_name}.png", :class => "featured-deck-img"
      .overlay= t "cards.featured_descriptions.#{desc_key}"

app/views/cards/_how_to_section.haml
%div{:class => ["how-to-section", (additional_class if local_assigns.has_key? :additional_class)]}>
  %h2.how-to-hdr= t how_to_path(hdr_key)
  %p.how-to-txt= t how_to_path(content_key)
  %p.how-to-txt.lp-link= t how_to_path(lp_key), :lp_path => lp_path

app/views/cards/_observer_card_images.haml
%ul.observer-card-images
  - images.each do |image|
    %li>
      = image_tag "observer_cards/#{image}"

app/views/cards/_observer_card_links.haml
%ul.observer-card-links
  %li.observer-card-link
    = link_to "observer_cards/#{type}_cards_ebook.pdf" do
      %i.fa.fa-2x.fa-book>
      %br
      = t(".#{type}_cards_ebook")
  %li.observer-card-link
    = link_to "observer_cards/#{type}_cards_print.pdf" do
      %i.fa.fa-2x.fa-download>
      %br
      = t(".download_printable_deck")

app/views/cards/_observer_cards_section.haml
.section
  %h3.section-head-cards{class: "section-head-cards-#{type}"}= t(".#{type}_cards_header")
  = render "observer_card_images", images: ["#{type}1.png", "#{type}2.png", "#{type}3.png"]
  %p.text.text-p.text-p-cards= t(".#{type}_cards_desc")
  = render "observer_card_links", type: type

app/views/cards/_organizer.haml
%li.organizer
  = link_to t(".#{title_key}"), "/card_resources/#{file_name}"

app/views/cards/_trait_step.haml
%li
  = image_tag "cards/step_icons/#{file_name}"
  %div= text

app/views/cards/index.haml
= render "shared/intro_section", header: "cards.index.intro_header", paragraphs: ["cards.index.intro_text1", "cards.index.intro_text2"]

.card-resources
  %ul.anchor-links
    %li.anchor-link.anchor-link-types>
      %a{href: "#CardTypes"}= t(".card_types_header")
    %li.anchor-link.anchor-link-tutorials>
      %a{href: "#Tutorials"}= t(".tutorials_header")
    %li.anchor-link.anchor-link-activities> 
      %a{href: "#Activities"}= t(".activities_header")
    %li.anchor-link.anchor-link-standards>
      %a{href: "#Standards"}= t(".data_resources_header")
.section
  %a#CardTypes.section-anchor
  %h3.section-head-cards.section-head-cards-types= t(".card_types_header")
  %p.text.text-p.text-p-cards= t(".card_types_text")
  %ul.cards<
    = render "card", image_file_name: "card_types/trait.png", name: t(".trait_name"), desc: t(".trait_desc")
    = render "card", image_file_name: "card_types/title.png", name: t(".title_name"), desc: t(".title_desc")
    = render "card", image_file_name: "card_types/project.png", name: t(".project_name"), desc: t(".project_desc")
    = render "card", image_file_name: "card_types/vocab.png", name: t(".vocabulary_name"), desc: t(".vocabulary_desc")
    = render "card", image_file_name: "card_types/key.png", name: t(".key_name"), desc: t(".key_desc")
.section
  %a#Tutorials.section-anchor
  %h3.section-head-cards.section-head-cards-tutorials= t(".tutorials_header")
  %p.text.text-p.text-p-cards= t(".tutorials_text")
  %ul.tutorials<
    = render "tutorial", icon_file_name: "create.png", file_name: "intro_to_cards.pdf", name: t(".intro_tutorial_title"), desc: t(".intro_tutorial_desc")
    = render "tutorial", icon_file_name: "manager.png", file_name: "how_to_make_cards.pdf", name: t(".how_to_make_tutorial_title"), desc: t(".how_to_make_tutorial_desc")
  %a#Activities.section-anchor
  %h3.section-head-cards.section-head-cards-activities= t(".activities_header")
  %p.text.text-p.text-p-cards= t(".activities_text")
  %ul.cards.cards-activity<
    = render "card", image_file_name: "activity_icons/blank_cards.png", name: t(".blank_cards_pdf"), desc: t(".blank_desc"), file_path: "activities/blank_species_card_packet.pdf"
    = render "card", image_file_name: "activity_icons/food_chain.png", name: t(".food_chain_template"), desc: t(".food_chain_desc"), file_path: "activities/foodchain.pdf"
    = render "card", image_file_name: "activity_icons/trophic_pyramid.png", name: t(".trophic_food_pyramid"), desc: t(".trophic_desc"), file_path: "activities/trophic_pyramid_eol_cards.pdf"
  %h4= t(".lesson_plans")
  %p.text.text-p.text-p-cards= t(".lesson_plans_intro_html", lesson_plans_path: lesson_plans_path)
  %ul.lesson-plans<
    = render "activity", lesson_plan: @food_chains_rummy, text: t(".food_chains_rummy_html")
    = render "activity", lesson_plan: @thats_classified, text: t(".thats_classified_html")
    = render "activity", lesson_plan: @go_adapt, text: t(".go_adapt_html")
    = render "activity", lesson_plan: @create_a_creature, text: t(".create_a_creature_html")
  %a#Standards.section-anchor
  %h3.section-head-cards.section-head-cards-standards= t(".data_resources_organizers_header")
  %p.text.text-p.text-p-cards= t(".research_tools_desc")
  %h4.trait-steps-hdr= t(".steps_header")
  %ul.trait-steps
    = render "trait_step", file_name: "choose_species.png", text: t(".steps.choose_species");
    = render "trait_step", file_name: "research.png", text: t(".steps.research_traits")
    = render "trait_step", file_name: "create.png", text: t(".steps.create_card")
    = render "trait_step", file_name: "publish.png", text: t(".steps.publish_card")

  %h4.sub-head= t(".data_subheader")
  .section-organizers
    .main-organizer>
      %p.text.text-p.text-p-cards.text-p-main-organizer= t(".intro_organizer")
      = link_to "card_resources/make_biodiversity_cards.pdf", class: "main-organizer-link" do
        = image_tag "cards/organizer_icons/intro_icon.png", class: "main-organizer-img"
        .main-organizer-title= t(".intro_organizer_title")
    %ul.organizers>
      = render "organizer", title_key: "example_cards", file_name: "card_examples.pdf"
      = render "organizer", title_key: "research", file_name: "card_research_organizer.docx"
      = render "organizer", title_key: "resources", file_name: "trait_research_resources.xlsx"
      = render "organizer", title_key: "biodiversity", file_name: "card_vocabulary.docx"
      = render "organizer", title_key: "data", file_name: "card_data_collection_template_simple.xlsx"
      = render "organizer", title_key: "data_advanced", file_name: "data_collection_template_advanced.xlsx"

app/views/cards/new.haml
%script#LabelTemplate{:type => "text/x-handlebars-template"}
  .label {{label}}

%script#TextInputTemplate{:type => "text/x-handlebars-template"}
  .fields
    %input.text-input.text-field{:id => "{{id}}", :value => "{{defaultVal}}"}

%script#TextareaTemplate{:type => "text/x-handlebars-template"}
  .fields
    %textarea.textarea.text-field{:id => "{{id}}"} {{defaultVal}}

%script#ImageInputTemplate{:type => "text/x-handlebars-template"}
  .fields.image-input{:id => "{{id}}"}
    .zoom-controls
      %i.fa.fa-minus-circle.fa-2x
      %i.fa.fa-plus-circle.fa-2x
    .img-selector
      :plain
        {{#each images}}
          <img class="thumb" src="{{this.src}}" data-index="{{this.index}}" data-credit="{{this.credit}}"/>
        {{/each}}
    .image-upload
      .upload-preview
      %input.image-upload-input{:type => "file"}
    .fields
      %label{:for => "{{id}}Credit"} Image credit:
      %input.text-input{:id => "{{id}}Credit", :class => "image-credit"}

%script#LabeledImageInputTemplate{:type => "text/x-handlebars-template"}
  .fields.labeled-image-input
    %select
      :plain
        {{#each images}}
          <option value="{{this.index}}">{{this.label}}</option>
        {{/each}}


%script#ColorInputTemplate{:type => "text/x-handlebars-template"}
  .fields.color-input
    .color-row
      :plain
        {{#each colors}}
          <div class="color" data-color="{{this}}" data-index="{{@index}}"></div>
        {{/each}}

%script#KeyValListInputTemplate{:type => "text/x-handlebars-template"}
  .fields.key-val-list
    :plain
      {{#each data}}
        <div class="key-val-wrap" data-index="{{this.index}}">
          <input class="key-input" type="text" value="{{this.key}}">
          <input class="val-input" type="text" value="{{this.val}}">
        </div>
      {{/each}}

%script#MultiImageTemplate{:type => "text/x-handlebars-template"}
  .fields.multi-image
    :plain
      {{#each images}}
        <div class="img-wrap" data-index="{{@index}}">
          <img src="{{this.url}}" class="img">
        </div>
      {{/each}}

%script#SpinnerTemplate{:type => "text/x-handlebars-template"}
  %i.fa.fa-spinner.fa-spin.fa-2x.img-placeholder

%script#CardPlaceholderTemplate{:type => "text/x-handlebars-template"}
  .resource-wrap.user-resource-wrap{:'data-card-id' => "{{cardId}}", :id => "Card-{{cardId}}"}
    .resource-frame.user-resource-frame
      %i.fa.fa-spinner.fa-spin.fa-2x.img-placeholder
    :plain
      {{#if decks}}
        <select class="deck-selector">
          <option value="none">(Not in deck)</option>
          {{#each decks}}
            <option value="{{this.id}}">{{this.name}}</option>
          {{/each}}
        </select>
      {{/if}}

%script#UserCardTemplate{:type => "text/x-handlebars-template"}
  %img.user-resource{:src => "{{src}}"}

%script#DeckTemplate{:type => "text/x-handlebars-template"}
  .resource-wrap.user-resource-wrap
    .resource-frame.user-resource-frame
      %i.fa.fa-image.fa-4x.title-card-placeholder
    .deck-name {{name}}

%script#CardOverlayTemplate{:type => "text/x-handlebars-template"}
  .card-overlay.resource-overlay
    %i.fa.fa-edit.fa-3x.edit-btn.btn
    %i.fa.fa-trash-o.fa-3x.trash-btn.btn

%script#DeckOverlayTemplate{:type => "text/x-handlebars-template"}
  .deck-overlay.resource-overlay
    %i.fa.fa-folder-open-o.fa-3x.edit-btn.btn
    %i.fa.fa-trash-o.fa-3x.trash-btn.btn

%script#UserDecksTemplate{ :type => "text/x-handlebars-template"}
  .deck-wrap.user-deck-wrap
  
%h1.new-card-hdr Card Generator Test Page

%h2.user-resources-hdr.card-hdr Card Manager
.card-manager-controls
  %ul#ViewSelector.view-selector
    %li.card-view.view.selected.first> Cards
    %li.deck-view.view> Decks
    %li.deck-cards-view.view.hidden>
.user-resources.user-decks#UserResources
  #NewResource.resource-wrap.new-resource
    .resource-frame
      %i.fa.fa-plus.fa-3x.new-resource-icon

%h2.create-card-hdr.card-hdr Card Editor
#CardGenerator.card-generator.hidden
  .left-col
    .controls#GeneratorControls

  .right-col
    #CanvasWrap
      %canvas.canvas#Canvas
      .btns-wrap
        %i#SaveBtn.fa.fa-floppy-o.fa-3x.save-btn.btn.last

app/views/cards/observer_cards.haml
= render "shared/intro_section", header: "cards.observer_cards.intro_header", paragraphs: %w(cards.observer_cards.intro_text)
= render "observer_cards_section", type: "bee"
= render "observer_cards_section", type: "frog"